---
title: "Mini-Project 2"
author: "Karina Lieb, Alexis Kilayko, and Olivia Baldwin"
date: "March 22, 2018"
output: 
  html_document:
    code_folding: show
---

```{r, include=FALSE}
#loading the data
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
```

ideas for what to display
- spending by state (which state's elections are most contributed to?)
- see if higher spending correlates with a win (relate spending, a specfic candidate, and win/lose)
- name and types/designations of the highest-contributing committees

```{r}
#spending by state (which state's elections are most contributed to?)

#wrangling
state_spending <- contributions %>%
  group_by(state) %>%
  summarise(total_cont = sum(transaction_amt)) %>%
  arrange(desc(total_cont))

#plotting
ggplot(data = state_spending, aes(x = reorder(state,-total_cont), y = total_cont)) +
  geom_col() +
  theme(axis.text.x = element_text(size = rel(0.9), angle = 80, hjust = 1))
```

```{r}
#see if higher spending correlates with a win (relate spending, a specfic candidate, and win/lose) 
#relate committee to candidate
#calculate spending by committee
#arrange that list by most to least money
#graph: x-axis is individual candidates, y is amount spent on thier committee, color is W/L
#one table with candidate ID, amount spent on them, and W/L

contributions_org <- contributions %>%
  select(cand_id, transaction_amt) %>%
  group_by(cand_id) %>%
  summarize(transaction_sum = sum(transaction_amt))

house_elections_org <- house_elections %>%
  select(fec_id, ge_winner, incumbent) %>%
  rename(cand_id = fec_id)

cand_spending <- inner_join(contributions_org, house_elections_org, by = "cand_id")

cand_spending <- cand_spending %>%
  mutate(new_incumbent = ifelse(incumbent == "TRUE", "Incumbent", "Not Incumbent"),
         new_ge_winner = ifelse(ge_winner == "W", "Win", "Loss"))

ggplot(data = cand_spending, aes(x = cand_id, y = transaction_sum, col = new_ge_winner)) +
  geom_point() +
  facet_wrap(~new_incumbent) +
  theme(axis.text.x = element_blank()) +
  ggtitle("Title") +
  labs(x = "Candidate", y = "Transaction Sum (dollars)", col = "Loss or Win") +
  scale_y_continuous(breaks = c(0e+00, 2e+06, 4e+06, 6e+06),
                     labels = c("0", "2,000,000", "4,000,000", "6,000,000"))

```

```{r}
# name and types/designations of the highest-contributing committees

# wrangling relevant variables from committee
committee_info <- committees %>%
  select(cmte_id, cmte_dsgn, org_type, cand_id)

# wrangling relevant data from contributions
contribution_info <- contributions %>%
  select(cmte_id, entity_type, transaction_amt, other_id, cand_id)

# joining the two observations
contri_commit <- committee_info %>%
  full_join(contribution_info, by = c("cmte_id", "cand_id"))

# graphing it
mutable_data <- contri_commit %>%
  filter(!is.na(org_type)) %>%
  group_by(org_type) %>%
  arrange(desc(transaction_amt))

ggplot(mutable_data, aes(x = org_type, y = transaction_amt, fill = cmte_dsgn)) +
  geom_bar(stat = "identity", position = position_dodge(), width  = 0.7) +
  theme(legend.position = "top")

# write a function for the graphical representation of this!
```
[^1]: Link to GitHub repository: https://github.com/akilayko/sds192-mp2
